//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDBApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Album
    {
        public int AlbumsID { get; set; }
        [Display(Name = "Album Name")]
        public string AlbumName { get; set; }
        public bool Grammy { get; set; }
        [Display(Name = "Cover Art")]
        public string AlbumCoverArt { get; set; }
        public int ArtistID { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
